mark actions failed when failing doctests

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -37,7 +37,17 @@ jobs:
       - name: Install package
         run: make install
       - name: Run doctests
-        run: make test
+        id: doctests
+        run: |
+          make test
+          echo $? > result.txt
+        continue-on-error: true
+      - name: Fail if doctests failed
+        run: |
+          if [ "$(cat result.txt)" != "0" ]; then
+            echo "Doctests failed"
+            exit 1
+          fi
         continue-on-error: true
       - name: Generate documentation
         run: make doc
